# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

splitStrCpp <- function(x, del) {
    .Call('_scShaper_splitStrCpp', PACKAGE = 'scShaper', x, del)
}

innerConnection <- function(x, y) {
    .Call('_scShaper_innerConnection', PACKAGE = 'scShaper', x, y)
}

cycle <- function(x, y) {
    .Call('_scShaper_cycle', PACKAGE = 'scShaper', x, y)
}

connectable <- function(x, y) {
    .Call('_scShaper_connectable', PACKAGE = 'scShaper', x, y)
}

replace <- function(str, from, to) {
    .Call('_scShaper_replace', PACKAGE = 'scShaper', str, from, to)
}

connectGraphs <- function(x, y) {
    .Call('_scShaper_connectGraphs', PACKAGE = 'scShaper', x, y)
}

specialKruskal <- function(d) {
    .Call('_scShaper_specialKruskal', PACKAGE = 'scShaper', d)
}

